DROP DATABASE IF EXISTS COOKIES;
CREATE DATABASE COOKIES;
USE COOKIES;

CREATE TABLE USUARIOS
(USUARIO VARCHAR(20),
 CONTRASENA VARCHAR(40) NOT NULL);
 
ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (USUARIO);
ALTER TABLE USUARIOS ADD CONSTRAINT UK_USUARIOS UNIQUE KEY (CON);


INSERT INTO USUARIOS (USUARIO, CONTRASENA) VALUES
('WILLIAM', 'WILLIAM1234'),
('JOEL', 'JOEL1234'),
('QUEVEDO', 'QUEVEDO1234'),
('ASIER', 'ASIER1234'),